// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNtNG6fN5OnszJRgdOBo5CL3zRmzJpGaY',
    appId: '1:123456789:web:abcdefghijklmnopqrstuvwxyz',
    messagingSenderId: '123456789',
    projectId: 'mend-ai-dev',
    authDomain: 'mend-ai-dev.firebaseapp.com',
    storageBucket: 'mend-ai-dev.appspot.com',
    measurementId: 'G-ABCDEFGHIJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp4r8PrvLCWYX9cPxbSVtv-cLL0xaD72c',
    appId: '1:571931343862:android:1361fcaf264c2177cda5d7',
    messagingSenderId: '571931343862',
    projectId: 'mend-ai-e582d',
    storageBucket: 'mend-ai-e582d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOn3_fiSgnGMOSzMYUU5AgHm-OZX8m_ZU',
    appId: '1:571931343862:ios:2e999fc8b8c0d486cda5d7',
    messagingSenderId: '571931343862',
    projectId: 'mend-ai-e582d',
    storageBucket: 'mend-ai-e582d.firebasestorage.app',
    iosBundleId: 'com.example.mendAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNtNG6fN5OnszJRgdOBo5CL3zRmzJpGaY',
    appId: '1:123456789:ios:abcdefghijklmnopqrstuvwxyz',
    messagingSenderId: '123456789',
    projectId: 'mend-ai-dev',
    storageBucket: 'mend-ai-dev.appspot.com',
    iosClientId: '123456789-abcdefghijklmnopqrstuvwxyz.apps.googleusercontent.com',
    iosBundleId: 'com.example.mendAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNtNG6fN5OnszJRgdOBo5CL3zRmzJpGaY',
    appId: '1:123456789:web:abcdefghijklmnopqrstuvwxyz',
    messagingSenderId: '123456789',
    projectId: 'mend-ai-dev',
    authDomain: 'mend-ai-dev.firebaseapp.com',
    storageBucket: 'mend-ai-dev.appspot.com',
    measurementId: 'G-ABCDEFGHIJ',
  );
}